# start-dev.ps1 -- generate the three per-service launch scripts and run them.
#
# Writes scripts/start-engine.ps1, scripts/start-backend.ps1 and
# scripts/start-frontend.ps1, then opens one PowerShell window per service so
# each keeps its own log stream and can be stopped with Ctrl+C independently.
#
#   .\start-dev.ps1                 generate the scripts and launch all three
#   .\start-dev.ps1 -GenerateOnly   write the scripts, launch nothing
#   .\start-dev.ps1 -SkipEngine     backend + frontend only (no Python needed)
#
# There is no root package manager in this repo, so every service is started
# from inside its own directory. Paths are resolved from this file's location,
# not the current directory, so it works from anywhere.

[CmdletBinding()]
param(
    [switch]$GenerateOnly,
    [switch]$SkipEngine
)

$ErrorActionPreference = 'Stop'

$root       = $PSScriptRoot
$scriptsDir = Join-Path $root 'scripts'

if (-not (Test-Path $scriptsDir)) {
    New-Item -ItemType Directory -Path $scriptsDir | Out-Null
}

# ---------------------------------------------------------------------------
# The three generated scripts.
#
# Single-quoted here-strings: everything inside is literal, so $PSScriptRoot is
# resolved when the generated script runs, not now. Each one re-derives the repo
# root itself rather than having a path baked in, so moving or renaming the
# checkout does not break them.
# ---------------------------------------------------------------------------

$engineScript = @'
# Generated by start-dev.ps1 -- engine-service on port 5000.
# Reads engine-service/.env (ENGINE_MODE, LLM_ENGINE, API_KEY, PORT).
$ErrorActionPreference = 'Stop'
$Host.UI.RawUI.WindowTitle = 'AutoRestTest - engine-service :5000'

$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'engine-service'
$activate = Join-Path $dir '.venv\Scripts\Activate.ps1'

if (-not (Test-Path $activate)) {
    Write-Host "No virtualenv at $activate" -ForegroundColor Red
    Write-Host "Create it first:" -ForegroundColor Yellow
    Write-Host "    cd `"$dir`"" -ForegroundColor Yellow
    Write-Host "    python -m venv .venv" -ForegroundColor Yellow
    Write-Host "    .venv\Scripts\pip install -r requirements.txt" -ForegroundColor Yellow
    Read-Host "`nPress Enter to close"
    exit 1
}

Set-Location $dir
. $activate

Write-Host "engine-service starting on http://127.0.0.1:5000" -ForegroundColor Cyan
Write-Host "(use 127.0.0.1, not localhost -- waitress is IPv4-only)`n" -ForegroundColor DarkGray

python wsgi.py

Write-Host "`nengine-service exited with code $LASTEXITCODE" -ForegroundColor Yellow
Read-Host "Press Enter to close"
'@

$backendScript = @'
# Generated by start-dev.ps1 -- NestJS backend on port 3000, watch mode.
$ErrorActionPreference = 'Stop'
$Host.UI.RawUI.WindowTitle = 'AutoRestTest - backend :3000'

$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'backend'

if (-not (Test-Path (Join-Path $dir 'node_modules'))) {
    Write-Host "Dependencies are not installed." -ForegroundColor Red
    Write-Host "Run: cd `"$dir`" ; npm install" -ForegroundColor Yellow
    Read-Host "`nPress Enter to close"
    exit 1
}

Set-Location $dir

Write-Host "backend starting on http://localhost:3000" -ForegroundColor Cyan
Write-Host "(needs DATABASE_URL and JWT_SECRET in backend/.env)`n" -ForegroundColor DarkGray

npm run start:dev

Write-Host "`nbackend exited with code $LASTEXITCODE" -ForegroundColor Yellow
Read-Host "Press Enter to close"
'@

$frontendScript = @'
# Generated by start-dev.ps1 -- Next.js frontend on port 3001.
$ErrorActionPreference = 'Stop'
$Host.UI.RawUI.WindowTitle = 'AutoRestTest - frontend :3001'

$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'frontend'

if (-not (Test-Path (Join-Path $dir 'node_modules'))) {
    Write-Host "Dependencies are not installed." -ForegroundColor Red
    Write-Host "Run: cd `"$dir`" ; npm install" -ForegroundColor Yellow
    Read-Host "`nPress Enter to close"
    exit 1
}

Set-Location $dir

Write-Host "frontend starting on http://localhost:3001" -ForegroundColor Cyan
Write-Host "(port 3001 because the backend owns 3000)`n" -ForegroundColor DarkGray

npm run dev

Write-Host "`nfrontend exited with code $LASTEXITCODE" -ForegroundColor Yellow
Read-Host "Press Enter to close"
'@

# ---------------------------------------------------------------------------
# Write them out
# ---------------------------------------------------------------------------

$services = @(
    @{ Name = 'engine-service'; File = 'start-engine.ps1';   Body = $engineScript;   Port = 5000; Delay = 4 }
    @{ Name = 'backend';        File = 'start-backend.ps1';  Body = $backendScript;  Port = 3000; Delay = 6 }
    @{ Name = 'frontend';       File = 'start-frontend.ps1'; Body = $frontendScript; Port = 3001; Delay = 0 }
)

Write-Host "Writing launch scripts to $scriptsDir" -ForegroundColor Cyan
foreach ($svc in $services) {
    $path = Join-Path $scriptsDir $svc.File
    # -Encoding utf8 explicitly: Set-Content otherwise defaults to the system
    # ANSI codepage, which mangles anything non-ASCII another tool reads back.
    Set-Content -Path $path -Value $svc.Body -Encoding utf8
    Write-Host "  $($svc.File)" -ForegroundColor DarkGray
}

if ($GenerateOnly) {
    Write-Host "`nGenerated only. Run them yourself, or re-run without -GenerateOnly." -ForegroundColor Green
    return
}

# A dev launcher that quietly mails real people is a bad surprise, so say so.
$backendEnv = Join-Path $root 'backend\.env'
if (Test-Path $backendEnv) {
    if ((Get-Content $backendEnv -Raw) -match '(?m)^\s*EMAIL_MODE\s*=\s*real') {
        Write-Host "`nNote: backend/.env has EMAIL_MODE=real -- verification codes," -ForegroundColor Yellow
        Write-Host "      reset links and run notifications will be sent for real." -ForegroundColor Yellow
        Write-Host "      Set EMAIL_MODE=mock to log them to the console instead." -ForegroundColor Yellow
    }
}

# ---------------------------------------------------------------------------
# Launch, in dependency order
# ---------------------------------------------------------------------------

Write-Host "`nOpening a window per service..." -ForegroundColor Cyan

foreach ($svc in $services) {
    if ($SkipEngine -and $svc.Name -eq 'engine-service') {
        Write-Host "  skipping engine-service" -ForegroundColor DarkGray
        continue
    }

    $path = Join-Path $scriptsDir $svc.File

    # -NoExit keeps the window up after a crash so the stack trace is readable.
    # -ExecutionPolicy Bypass applies to the child only and avoids the generated
    # scripts being blocked on a machine with a restrictive default policy.
    Start-Process -FilePath 'powershell.exe' -ArgumentList @(
        '-NoExit'
        '-ExecutionPolicy', 'Bypass'
        '-File', "`"$path`""
    ) | Out-Null

    Write-Host "  $($svc.Name) -> port $($svc.Port)" -ForegroundColor Green

    # Staggered: the backend polls engine-service and the frontend calls the
    # backend, so starting them in order avoids a burst of connection errors
    # in the logs while the earlier service is still binding its port.
    if ($svc.Delay -gt 0) { Start-Sleep -Seconds $svc.Delay }
}

Write-Host "`nAll set. Open http://localhost:3001" -ForegroundColor Green
Write-Host "Stop a service with Ctrl+C in its own window." -ForegroundColor DarkGray
