[spec]
location = "D:\\SPL3\\AutoRestTest\\engine-service\\jobs\\b4839965b13f4ea2b6dff19f2fe3a9b2\\spec_3a18855792a189e1.yaml"
recursion_limit = 50
strict_validation = false

[llm]
engine = "openai/gpt-oss-20b"
creative_temperature = 1
strict_temperature = 1
api_base = "https://integrate.api.nvidia.com/v1"
max_tokens = 4096
rpm_limit = 40

[agents.header]
enabled = false

[agent]
max_combinations = 12
max_total_combinations = 3000
base_samples_per_size = 200
combination_seed = 42

[agent.value]
parallelize = true
max_workers = 3

[cache]
use_cached_graph = false
use_cached_table = false

[export]
dependency_graph = true

[q_learning]
learning_rate = 0.1
discount_factor = 0.9
max_exploration = 1

[request_generation]
time_duration = 1200
mutation_rate = 0.2

[api]
override_url = false
host = "localhost"
port = 8080

[custom_headers]
Authorization = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNWRkMDA5MGI2NzQ3Yzg5OWViNTJlMzJlMzA0N2NiYzc2MWEwNDAwZjE0MjZhMTFmOWI5MTk2MGE5MTFjMGJlMzdiYWM0YzAyYTBhODY2NTYiLCJpYXQiOjE3ODcyMzQwNjYuMjc0NTYsIm5iZiI6MTc4NzIzNDA2Ni4yNzQ1NjIsImV4cCI6MzA0OTUzODA2Ni4yNTg2MDksInN1YiI6IjEiLCJzY29wZXMiOltdfQ.ZSxeoTLeyt2dY1zZQ0JMrJc_KjPmNfa_zXCbslKSa0q1jbvZ1JO96WDHTkUbEZuJACsZk1-4kH3IELoTE7WNpMGYmrCa-jxO4Co7qT0beVT0ceXGXZ0dZpvm70sP1hnQ1xSSz_CNK4LDaStwd6AzchxI17ndlGPFByg1pyicfdq2m98cdKCT4rEdr6Zu7vEkEwonKdJ2OIVx1dqtHai0mfOJdH95_Ukqt53JNohSlmsMgY8ofj3GzlIqR3oDFklAcXaHWorm4k4obw72Y6Cfl0CcuJCgLcUYztyYP4EtnkyloU6mmpvllKSwuQQQYC8Qlme4_Q5ZjnsNOQZb6wNJG89YpW_LG4y2q2QPz6uzf0PiLPltlKbYP9_2pMMFs3DDIsJ9q4YEsyBjYO05prGUOwS7VDwqz4526PCNllUSqiXktuOBjCCqwWK5I5G6CFUGqGf3y0F-QwbPr4t2he4f5GaiVnYajbnoK6iRmU6dT9DCywEpIehTkOC-wdWH12uaQFQTawurndYS4tC3ES2JGrRdtITq9I3YHv37mn67cMx3C6u6l7XwVbF424-_QeTL-n3zYztm5k5sEwiNt49I2vqXy88KYqv4GqW9YnYrhWcVzc5B6hoVyWXvFY2SjtBfepcCA7i8kn0BJTkNJzDZmAru0erhBKLJhuVjr0Fzwag"
