[spec]
location = "D:\\SPL 3\\AutoRestTest\\engine-service\\jobs\\7e5fa99ece1d46ef8b39815e62156f7a\\job_7e5fa99ece1d.yaml"
recursion_limit = 50
strict_validation = false

[llm]
engine = "openai/gpt-oss-20b:free"
creative_temperature = 1
strict_temperature = 1
api_base = "https://openrouter.ai/api/v1"
max_tokens = 30000

[agents.header]
enabled = false

[agent]
max_combinations = 12
max_total_combinations = 3000
base_samples_per_size = 200
combination_seed = 42

[cache]
use_cached_graph = false
use_cached_table = false

[q_learning]
learning_rate = 0.1
discount_factor = 0.9
max_exploration = 1

[request_generation]
time_duration = 300
mutation_rate = 0.2

[api]
override_url = false
host = "localhost"
port = 8080

[custom_headers]
Authorization = "Bearer ${JWT_TOKEN}"
