# Generated by start-dev.ps1 -- NestJS backend on port 3000, watch mode.
$ErrorActionPreference = 'Stop'
$Host.UI.RawUI.WindowTitle = 'AutoRestTest - backend :3000'

$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'backend'

if (-not (Test-Path (Join-Path $dir 'node_modules'))) {
    Write-Host "Dependencies are not installed." -ForegroundColor Red
    Write-Host "Run: cd `"$dir`" ; npm install" -ForegroundColor Yellow
    Read-Host "`nPress Enter to close"
    exit 1
}

Set-Location $dir

Write-Host "backend starting on http://localhost:3000" -ForegroundColor Cyan
Write-Host "(needs DATABASE_URL and JWT_SECRET in backend/.env)`n" -ForegroundColor DarkGray

npm run start:dev

Write-Host "`nbackend exited with code $LASTEXITCODE" -ForegroundColor Yellow
Read-Host "Press Enter to close"
