# Generated by start-dev.ps1 -- Next.js frontend on port 3001.
$ErrorActionPreference = 'Stop'
$Host.UI.RawUI.WindowTitle = 'AutoRestTest - frontend :3001'

$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'frontend'

if (-not (Test-Path (Join-Path $dir 'node_modules'))) {
    Write-Host "Dependencies are not installed." -ForegroundColor Red
    Write-Host "Run: cd `"$dir`" ; npm install" -ForegroundColor Yellow
    Read-Host "`nPress Enter to close"
    exit 1
}

Set-Location $dir

Write-Host "frontend starting on http://localhost:3001" -ForegroundColor Cyan
Write-Host "(port 3001 because the backend owns 3000)`n" -ForegroundColor DarkGray

npm run dev

Write-Host "`nfrontend exited with code $LASTEXITCODE" -ForegroundColor Yellow
Read-Host "Press Enter to close"
