# Generated by start-dev.ps1 -- engine-service on port 5000.
# Reads engine-service/.env (ENGINE_MODE, LLM_ENGINE, API_KEY, PORT).
$ErrorActionPreference = 'Stop'
$Host.UI.RawUI.WindowTitle = 'AutoRestTest - engine-service :5000'

$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'engine-service'
$activate = Join-Path $dir '.venv\Scripts\Activate.ps1'

if (-not (Test-Path $activate)) {
    Write-Host "No virtualenv at $activate" -ForegroundColor Red
    Write-Host "Create it first:" -ForegroundColor Yellow
    Write-Host "    cd `"$dir`"" -ForegroundColor Yellow
    Write-Host "    python -m venv .venv" -ForegroundColor Yellow
    Write-Host "    .venv\Scripts\pip install -r requirements.txt" -ForegroundColor Yellow
    Read-Host "`nPress Enter to close"
    exit 1
}

Set-Location $dir
. $activate

Write-Host "engine-service starting on http://127.0.0.1:5000" -ForegroundColor Cyan
Write-Host "(use 127.0.0.1, not localhost -- waitress is IPv4-only)`n" -ForegroundColor DarkGray

python wsgi.py

Write-Host "`nengine-service exited with code $LASTEXITCODE" -ForegroundColor Yellow
Read-Host "Press Enter to close"
